%YAML:1.0 # need to specify the file type at the top!

cam0:
  T_cam_imu: #rotation from IMU to camera R_ItoC, position of IMU in camera p_IinC
    - [1.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: equidistant
  intrinsics: [525.0, 525.0, 319.5, 239.5]
  resolution: [640, 480] # width x height
  rgb_rostopic: /camera/rgb/image_color

  use_sensor_detph: 1
  sensor_depth_rostopic: /camera/depth/image

  use_learned_depth: 0
  model_name_learned_depth: model-v21-small-traced.pt
  output_learned_depth_rostopic: /camera/learned_depth/image

  use_learned_object_detection: 0
  model_name_learned_object_detection: yolov8n.cuda.torchscript
  learned_object_detection_rostopic: /camera/object_detection/image

  use_learned_semantic_segmentation: 0
  model_name_learned_semantic_segmentation: yolov8s-seg.torchscript
  learned_semantic_segmentation_rostopic: /camera/semantic_segmentation/image






