%YAML:1.0 # need to specify the file type at the top!

commond:
  placeholder: 1

ORB:
  num_feature_points: 2000
  block_size: 60 # seperate image int multiple block with block_size x block_size
  fastThreshold: 20
  useNonmaxSuppression: 1
  threshold_for_tracking_descriptor_in_time: 30.0 # for tracking cross time
  threshold_for_tracking_descriptor_in_frame: 40.0 # for tracking cross images in same frame
  matching_ratio: 2.0 # distance of matching point < min_distance * matching_ratio

KLT:
  num_feature_points: 200
  min_distance: 10 # min distance between two features
  max_count: 30 # Max number of iterations (used if COUNT is set)
  epsilon: 0.01 # Min required accuracy / threshold (used if EPS is set)