%YAML:1.0 # need to specify the file type at the top!

system:
  log_verbosity: "VERBOSE" # VERBOSE, KEY, QUIET
  max_cameras: 1 # number of cameras, 2 for stereo, 1 for monocular
  max_imus: 1 # number of IMUs
  max_stereo_time_offset: 0.02 # max time offset for stereo image pair (unit: second)
  max_color_sensor_depth_pair_time_offset: 0.02 # max time offset for image pair for bgr and depth (unit: second)

  # feature detect and tracking
  feature_and_tracker_config_name: feature_and_tracker_config.yaml

  #initialization and visual frontend
  threshold_for_pnp_pose_log_norm: 0.2 # estimated pose can't too large
  min_inliers: 20
  minimum_cumulative_translation: 0.2
  maximum_num_fail: 2  # when number of fail of pose estimation  reach this, state turn to get lost.



  # backend
  minimum_key_frame_translation: 0.5


  # map
  max_num_local_map_size: 20000000


  # relative config file name
  imu_config_name: "imu_config.yaml"
  camera_config_name: "camera_config.yaml"
  visualizer_config_name: "visualizer_config.yaml"

  # model
  model_path: /root/catkin_ws/src/modules_vins/models

  # ground truth
  use_groundtruth_pose: 1
  set_first_GT_pose_in_origin: 1
  #groundtruth path
  max_tolerant_gt_time_offset: 0.02
  # please remember switch gt file
  groundtruth_path: /root/datasets2/tum/rgbd_dataset_freiburg1_desk/groundtruth.txt
  T_cam_GT: #transformation from camera to GT, we only need rotation actually
    - [1, 0, 0, 0]
    - [0, 1, 0, 0]
    - [0, 0, 1, 0]
    - [0, 0, 0, 1]
  #output
  output_dir: /root/catkin_ws/src/modules_vins/evaluation_results

  # debug
  check_triangulation: 0


  