%YAML:1.0 # need to specify the file type at the top!

system:
  log_verbosity: "VERBOSE" # VERBOSE, KEY, QUIET
  max_cameras: 2 # number of cameras, 2 for stereo, 1 for monocular
  max_imus: 1 # number of IMUs
  max_stereo_time_offset: 0.02 # max time offset for stereo image pair (unit: second)
  max_color_sensor_depth_pair_time_offset: 0.02 # max time offset for image pair for bgr and depth (unit: second)

  # feature detect and tracking
  feature_and_tracker_config_name: feature_and_tracker_config.yaml

  #initialization and visual frontend
  threshold_for_pnp_pose_log_norm: 0.5 # estimated pose can't too large
  min_inliers: 20
  minimum_cumulative_translation: 0.2
  maximum_num_fail: 2  # when number of fail of pose estimation  reach this, state turn to get lost.

  #depth (unit meter)
  maximum_estimated_depth: 120 # exceced this threshold, will be ignored
  minimum_estimated_depth: 0.1 # exceced this threshold, will be ignored


  # backend
  minimum_key_camera_frame_translation: 0.5


  # map
  max_num_local_map_size: 2000000

  # relative config file name
  imu_config_name: "imu_config.yaml"
  camera_config_name: "camera_config.yaml"
  visualizer_config_name: "visualizer_config.yaml"
  comparison_config_name: "comparison.yaml"

  # model
  model_path: /root/catkin_ws/src/modules_vins/models

  #robot_base, it have to be the name of each sensor, like imu0, cam0, cam1, or even comparison, like GT, VINSFUSION
  robot_base: "imu0"

  #groundtruth path
  use_comparison_pose_for_pose_estimation: 0 #if you set this to 1, then set robot_base to corresponding frame
  # comparison_pose_idx_for_pose_estimation: 0 # GT means ground truth

  # output
  output_dir: /root/catkin_ws/src/modules_vins/evaluation_results


  # debug
  check_triangulation: 0


  