%YAML:1.0 # need to specify the file type at the top!

visualizer:
  # visualization tool
  use_opencv_vis: 1
  use_pangolin_vis: 0
  use_rviz_vis: 1

opencv_visualizer:
  show_projected_mappoint: 0
  show_matching_in_frame: 1
  show_matching_in_time: 1
  show_tracking_in_time: 1
  show_sensor_depth: 1
  show_stereo_depth: 1
  show_learned_stereo_disparity: 0
  show_learned_depth: 0
  show_object_detection: 1
  show_semantic_segmentation: 1


pangolin_visualizer:
  frame_size: 0.1
  point_size: 2.0
  trajectory_line_size: 1.0
  viewer_eye_positionX: 0.0
  viewer_eye_positionY: -0.7
  viewer_eye_positionZ: -1.8
  show_groundtruth_trajectory: 1
  show_groundtruth_pose: 1


rviz_visualizer:
  output_pose_rostopic: /output/camera_pose
  output_key_frame_poses_rostopic: /output/key_camera_poses
  output_trajectory_rostopic: /output/trajectory
  output_tracked_map_points_rostopic: /output/tracked_points
  show_groundtruth_trajectory: 1
  output_groundtruth_trajectory_rostopic: /output/groundtruth_trajectory
  show_groundtruth_pose: 1
  output_groundtruth_pose_rostopic: /output/groundtruth_pose


  




  